export const bnTranslations = {
  common: {
    gontobbo: "গন্তব্য",
    gontobboSlogan: "অনন্য ভ্রমণ, স্মরণীয় মুহূর্ত।",
    back: "ফিরে যান",
    lang: "বাংলা",
    or: "অথবা",
    home: "হোম",
    explore: "অন্বেষণ",
    offers: "অফার",
    wishlist: "ইচ্ছার তালিকা",
    profile: "প্রোফাইল",
    bookings: "বুকিংস",
  },
  login: {
    continueWithApple: "অ্যাপল দিয়ে চালিয়ে যান",
    continueWithFacebook: "ফেসবুক দিয়ে চালিয়ে যান",
    continueWithGmail: "জিমেইল দিয়ে চালিয়ে যান",
    loginWithEmail: "ইমেইল দিয়ে লগইন করুন",
    registerWithEmail: "ইমেইল দিয়ে রেজিস্টার করুন",
    continueAsGuest: "অতিথি হিসাবে চালিয়ে যান",
    termsAndConditions:
      "চালিয়ে যাওয়ার মাধ্যমে আপনি আমাদের শর্তাবলীতে সম্মতি দেন। আমরা আপনাকে একটি ব্যক্তিগতকৃত অভিজ্ঞতা প্রদানের জন্য আপনার ডেটা ব্যবহার করি।",
    findMore: "আরও জানুন",
    password: "পাসওয়ার্ড",
    dontHaveAnAccount: "অ্যাকাউন্ট নেই? ",
    firstName: "প্রথম নাম",
    lastName: "শেষ নাম",
    emailAddress: "ইমেইল ঠিকানা",
    enterPassword: "পাসওয়ার্ড লিখুন",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    phoneNumber: "ফোন নম্বর",
    haveAnAccount: "অ্যাকাউন্ট আছে? ",
    withEmail: "ইমেইল দিয়ে",
    login: "লগইন",
    register: "রেজিস্টার",
  },
  register: {
    register: "রেজিস্টার",
    registerWithEmail: "ইমেইল দিয়ে রেজিস্টার করুন",
    firstName: "প্রথম নাম",
    lastName: "শেষ নাম",
    emailAddress: "ইমেইল ঠিকানা",
    enterPassword: "পাসওয়ার্ড লিখুন",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    phoneNumber: "ফোন নম্বর",
    haveAnAccount: "অ্যাকাউন্ট আছে? ",
    login: "লগইন",
  },
  heartBeats: {
    heartBeat: "হার্টবিট",
    selectStartAndEnd: "স্মুদ প্লেব্যাকের জন্য শুরু এবং শেষ পয়েন্ট নির্বাচন করুন",
  },
  Home: {
    askAi: "প্রশ্ন করুন AI",
    askMeAnything: "আমার কাছে যা খুঁজছেন তা প্রশ্ন করুন",
    featureHotels: "বৈশিষ্ট্যযুক্ত হোটেল",
    popularTrip: "জনপ্রিয় ভ্রমণ",
  },
  Profile: {
    title: "প্রোফাইল",
    personalDetails: "ব্যক্তিগত বিবরণ",
    personalInfo: "ব্যক্তিগত তথ্য",
    passportDetails: "পাসপোর্ট বিবরণ",
    paymentMethods: "পেমেন্ট পদ্ধতি",
    flightPreferences: "ফ্লাইট পছন্দ",
    general: "সাধারণ",
    flightInformation: "ফ্লাইট তথ্য",
    travelRequirement: "ভ্রমণ প্রয়োজনীয়তা",
    baggages: "ব্যাগ",
    legal: "আইনি",
    logout: "লগ আউট",
    language: "ভাষা",
    memberCard: "মেম্বার কার্ড",
    signInProvider: "সাইন ইন প্রদানকারী",
    wishList: "উইশ লিস্ট",
    wishlistEmpty: "উইশ লিস্ট খালি!",
    tapTheHeartButtonToStartSaving: "হার্ট বাটন ট্যাপ করে সংরক্ষণ করতে শুরু করুন",
  },
};
