import { ImageSourcePropType } from "react-native";

export const images = {
  appLogo: require("@/assets/logo.png") as ImageSourcePropType,
  backgroundTexture: require("@/assets/Bg_texture.png") as ImageSourcePropType,
  home: require("@/assets/bottomTab/home.png") as ImageSourcePropType,
  homeActive: require("@/assets/bottomTab/homeActive.png") as ImageSourcePropType,
  explore: require("@/assets/bottomTab/explore.png") as ImageSourcePropType,
  exploreActive: require("@/assets/bottomTab/exploreActive.png") as ImageSourcePropType,
  offer: require("@/assets/bottomTab/offer.png") as ImageSourcePropType,
  offerActive: require("@/assets/bottomTab/offerActive.png") as ImageSourcePropType,
  wishlist: require("@/assets/bottomTab/wishlist.png") as ImageSourcePropType,
  wishlistActive: require("@/assets/bottomTab/wishlistActive.png") as ImageSourcePropType,
  profile: require("@/assets/bottomTab/profile.png") as ImageSourcePropType,
  profileActive: require("@/assets/bottomTab/profileActive.png") as ImageSourcePropType,
  appleIcon: require("@/assets/login/appleIcon.png") as ImageSourcePropType,
  fbIcon: require("@/assets/login/facebookIcon.png") as ImageSourcePropType,
  gmailIcon: require("@/assets/login/gmailIcon.png") as ImageSourcePropType,
  emailIcon: require("@/assets/login/emailIcon.png") as ImageSourcePropType,

  menuBtn: require("@/assets/menu_button.png") as ImageSourcePropType,
  notifiocationBtn: require("@/assets/notification_button.png") as ImageSourcePropType,

  magicAiBtn: require("@/assets/magic_ai_button.png") as ImageSourcePropType,
  dummyCard: require("@/assets/Home/dummyCard.png") as ImageSourcePropType,
  dummyTrip1: require("@/assets/Home/dummyTip.png") as ImageSourcePropType,
  dummyTri2: require("@/assets/Home/dummyTip2.png") as ImageSourcePropType,
  avatar1: require("@/assets/Home/avatar1.png") as ImageSourcePropType,
  avatar2: require("@/assets/Home/avatar2.png") as ImageSourcePropType,
  back: require("@/assets/Back.png") as ImageSourcePropType,
  showPassword: require("@/assets/login/showPassword.png") as ImageSourcePropType,
  initOne: require("@/assets/init/initOne.png") as ImageSourcePropType,
  initTwo: require("@/assets/init/initTwo.png") as ImageSourcePropType,
  initThree: require("@/assets/init/initThree.png") as ImageSourcePropType,
  languegeIcon: require("@/assets/Drawer/languegeIcon.png") as ImageSourcePropType,
  logoutIcon: require("@/assets/Drawer/logoutIcon.png") as ImageSourcePropType,
  myBookingIcon: require("@/assets/Drawer/myBookingIcon.png") as ImageSourcePropType,
  rateUsIcon: require("@/assets/Drawer/rateUsIcon.png") as ImageSourcePropType,
  referIcon: require("@/assets/Drawer/referIcon.png") as ImageSourcePropType,
  savedIcon: require("@/assets/Drawer/savedIcon.png") as ImageSourcePropType,
  supportIcon: require("@/assets/Drawer/supportIcon.png") as ImageSourcePropType,
  flightIcon: require("@/assets/flight.png") as ImageSourcePropType,
  plane: require("@/assets/plane.png") as ImageSourcePropType,
  bin: require("@/assets/bin.png") as ImageSourcePropType,
  map: require("@/assets/map.png") as ImageSourcePropType,
  success: require("@/assets/success.png") as ImageSourcePropType,
  rightArrow: require("@/assets/rightArrow.png") as ImageSourcePropType,
  barCode: require("@/assets/barcode.png") as ImageSourcePropType,
  applePay: require("@/assets/applePay.png") as ImageSourcePropType,
  creditCard: require("@/assets/creditCard.png") as ImageSourcePropType,
  pInfo: require("@/assets/profile/info.png") as ImageSourcePropType,
  pDetails: require("@/assets/profile/details.png") as ImageSourcePropType,
  pMethods: require("@/assets/profile/payment.png") as ImageSourcePropType,
  pFlight: require("@/assets/profile/flight.png") as ImageSourcePropType,
  pReq: require("@/assets/profile/req.png") as ImageSourcePropType,
  pBag: require("@/assets/profile/Baggages.png") as ImageSourcePropType,
  pLegal: require("@/assets/profile/legal.png") as ImageSourcePropType,
};
export type ImagesType = typeof images;
// export type Image = keyof ImagesType;
